site_name: E-Fidget
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: deep purple
      accent: light blue
  logo: img/logo.svg
  favicon: img/logo.svg
extra_css:
  - styles/header.css
  - styles/logo-spin.css
